services:
  - type: web
    name: ImageConverter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Converter:app -b 0.0.0.0:$PORT
    region: oregon
    branch: main
    runtime: python
