services:
  - type: web
    name: ImageConverter
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Converter:app -b 0.0.0.0:$PORT --timeout 60 --workers 2 --log-level info
    region: oregon
    branch: main
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
